export const ACTION_TYPES = {
    CHANGE_ICON: 'CHANGE_ICON',
    CLOSE_DROPDOWN: 'CLOSE_DROPDOWN',
    DISABLE_CURRENCY: 'DISABLE_CURRENCY',
    SHOW_MODAL: 'SHOW_MODAL',
    SHOW_ITEM_QUANTITY: 'SHOW_ITEM_QUANTITY',
    SAVE_ORDER_DATA: 'SAVE_ORDER_DATA',
    SAVE_TABNAME: 'SAVE_TABNAME',
    SAVE_PRODUCT_ID: 'SAVE_PRODUCT_ID',
    SAVE_CARTICON_CLICK: 'SAVE_CARTICON_CLICK',
    SAVE_PRODUCT_DATA:  'SAVE_PRODUCT_DATA',
    SAVE_PRODUCT_COUNT: "SAVE_PRODUCT_COUNT"
}
